#!/bin/bash
#©This Script is made by Crazy
apt upgrade -y #update termux
apt install zip && unzip #zip install
clear
echo -e "\e[32m
░█████╗░██████╗░░█████╗░███████╗██╗░░░██╗
██╔══██╗██╔══██╗██╔══██╗╚════██║╚██╗░██╔╝
██║░░╚═╝██████╔╝███████║░░███╔═╝░╚████╔╝░
██║░░██╗██╔══██╗██╔══██║██╔══╝░░░░╚██╔╝░░
╚█████╔╝██║░░██║██║░░██║███████╗░░░██║░░░
░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝░░░╚═╝░░░\e[0m"
echo -e "\033[33m𝙒𝙚𝙡𝙘𝙤𝙢𝙚 𝙩𝙤 𝙩𝙝𝙚 𝙨𝙘𝙧𝙞𝙥𝙩 𝙨𝙚𝙡𝙚𝙘𝙩 𝙩𝙝𝙚 𝙤𝙥𝙩𝙞𝙤𝙣 𝙩𝙤 𝘾𝙤𝙣𝙩𝙞𝙣𝙪𝙚:\033[0m"
echo -e "\033[33m1. 
█ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░
█ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄

▀▄▀ █▀▀ █▀▀ █▀▀
█░█ █▀░ █▄▄ ██▄\033[0m"
echo -e "\033[33m2. 
█▄▄ ▄▀█ █▀▀ █▄▀ █░█ █▀█   ▄▀█ █▄░█ █▀▄
█▄█ █▀█ █▄▄ █░█ █▄█ █▀▀   █▀█ █░▀█ █▄▀

█▀█ █▀▀ █▀ ▀█▀ █▀█ █▀█ █▀▀
█▀▄ ██▄ ▄█ ░█░ █▄█ █▀▄ ██▄\033[0m"
echo -e "\033[33m3. 
█░█ █▀█ █▀▀ █▀█ ▄▀█ █▀▄ █▀▀
█▄█ █▀▀ █▄█ █▀▄ █▀█ █▄▀ ██▄

█▀ █▀▀ █▀█ █ █▀█ ▀█▀
▄█ █▄▄ █▀▄ █ █▀▀ ░█░\033[0m"
echo -e "\033[33m4. 
█ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░
█ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄

█▀▀ █░░ █
█▄▄ █▄▄ █\033[0m"
echo -e "\033[33m5. 
█▀█ █░█ █ ▀█▀
▀▀█ █▄█ █ ░█░\033[0m"

read -p "Enter your choice: " choice

case $choice in
  1) echo "Installing OS..."
 options=("xfce" "Quit")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
    "xfce")
    
termux-setup-storage

pkg install root-repo x11-repo
pkg install neofetch -y

#installing xfce desktop

pkg install xfce* libxfce* mousepad tigervnc -y

echo "vncserver -geometry 1600x900 -name remote-desktop :1" > $PREFIX/bin/desktop-xfce
echo "vncserver -kill :1" > $PREFIX/bin/desktop-stop

mkdir ~/.vnc
echo "#!/bin/bash
xrdb $HOME/.Xresources
startxfce4" > ~/.vnc/xstartup

chmod +x ~/.vnc/xstartup
chmod +x $PREFIX/bin/desktop-xfce
chmod +x $PREFIX/bin/desktop-stop

clear
echo " "
echo "Vnc Server address will run at 127.0.0.1:5901"
echo " "
echo "Command to start 'desktop-xfce' and stop 'desktop-stop'"
echo " "

bash desktop-xfce
    ;;
    
    "Quit")
      echo "backing"
      cd ~/crazy && bash crazy
      break
      ;;
    *) echo "Invalid option"
      ;;
  esac
done
;;
  2) echo "Backing up and restoring..."
  cd /sdcard && mkdir backup
     options=("termux" "games" "Quit")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
"termux")
options=("backup" "restore" "back")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
"backup")
tar -zcf /sdcard/backup/termux-backup.tar.gz -C /data/data/com.termux/files ./home ./usr
;;
"restore")
tar -zxf /sdcard/TeraBoxDownloads/From：IN_Note1/backup/termux-backup.tar.gz -C /data/data/com.termux/files --recursive-unlink --preserve-permissions
;;
"back")
cd ~/crazy && bash crazy
 exit 0
      ;;
    *) echo "Invalid option"
      ;;
  esac
done
;;
"games")
options=("backup" "restore" "back")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
"backup")
cd /sdcard/android/data
zip -r com.astragon.cs3.zip com.astragon.cs3
mv com.astragon.cs3.zip /sdcard/backup
;;
"restore")
cd /sdcard/TeraBoxDownloads/From：IN_Note1/backup
cp com.astragon.cs3.zip /sdcard/android/data
cd /sdcard/android/data
unzip com.astragon.cs3.zip
rm -rf com.astragon.cs3.zip
;;

"back")
cd ~/crazy && bash crazy
exit 0
      ;;
      
    *) echo "Invalid option"
      ;;
  esac
done
;;
"Quit")
      echo "backing"
      cd ~/crazy && bash crazy
      break
      ;;
    *) echo "Invalid option"
      ;;
  esac
done
;;
  3) echo "Upgrading script..."
  cd ~
  rm -rf crazy
git clone https://github.com/sajanchhetri/crazy
cd ~/crazy && bash crazy
     ;;
  4) echo "CLI INSTALLATION"
   options=("KALI" "UBUNTU" "Quit")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
 "KALI")
 cd
 termux-setup-storage
pkg install wget
wget -O install-nethunter-termux https://offs.ec/2MceZWr
chmod +x install-nethunter-termux
./install-nethunter-termux
;;
"UBUNTU")
cd
apt upgrade -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu22/ubuntu22.sh -O ubuntu22.sh && chmod +x ubuntu22.sh && bash ubuntu22.sh
;;
"Quit")
cd ~/crazy && bash crazy
break
;;
    *) echo "Invalid option"
      ;;
  esac
done
;;
  5) echo "Quitting..."
     exit 0
     ;;
  *) echo "Invalid option. Please try again."
     ;;
esac