#!/bin/bash
#©This Script is made by Crazy
apt upgrade -y #update termux
apt install zip && unzip #zip install
clear
echo -e "\e[32m
░█████╗░██████╗░░█████╗░███████╗██╗░░░██╗
██╔══██╗██╔══██╗██╔══██╗╚════██║╚██╗░██╔╝
██║░░╚═╝██████╔╝███████║░░███╔═╝░╚████╔╝░
██║░░██╗██╔══██╗██╔══██║██╔══╝░░░░╚██╔╝░░
╚█████╔╝██║░░██║██║░░██║███████╗░░░██║░░░
░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝░░░╚═╝░░░\e[0m"
echo -e "\033[33m𝙒𝙚𝙡𝙘𝙤𝙢𝙚 𝙩𝙤 𝙩𝙝𝙚 𝙨𝙘𝙧𝙞𝙥𝙩 𝙨𝙚𝙡𝙚𝙘𝙩 𝙩𝙝𝙚 𝙤𝙥𝙩𝙞𝙤𝙣 𝙩𝙤 𝘾𝙤𝙣𝙩𝙞𝙣𝙪𝙚:\033[0m"
echo -e "\033[33m1. 
█ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░
█ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄

▀▄▀ █▀▀ █▀▀ █▀▀
█░█ █▀░ █▄▄ ██▄\033[0m"
echo -e "\033[33m2.
█ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░
█ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄

█░█ ▄▀█ █▀▀ █▄▀ █ █▄░█ █▀▀   ▀█▀ █▀█ █▀█ █░░ █▀
█▀█ █▀█ █▄▄ █░█ █ █░▀█ █▄█   ░█░ █▄█ █▄█ █▄▄ ▄█\033[0m"
echo -e "\033[33m3. 
█░█ █▀█ █▀▀ █▀█ ▄▀█ █▀▄ █▀▀
█▄█ █▀▀ █▄█ █▀▄ █▀█ █▄▀ ██▄

█▀ █▀▀ █▀█ █ █▀█ ▀█▀
▄█ █▄▄ █▀▄ █ █▀▀ ░█░\033[0m"
echo -e "\033[33m4. 
█ █▄░█ █▀ ▀█▀ ▄▀█ █░░ █░░
█ █░▀█ ▄█ ░█░ █▀█ █▄▄ █▄▄

█▀▀ █░░ █
█▄▄ █▄▄ █\033[0m"
echo -e "\033[33m5. 
█▀█ █░█ █ ▀█▀
▀▀█ █▄█ █ ░█░\033[0m"

read -p "Enter your choice: " choice

case $choice in
  1) echo "Installing OS..."
 options=("xfce" "Quit")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
    "xfce")
    cd
termux-setup-storage

pkg install root-repo x11-repo
pkg install neofetch -y

#installing xfce desktop

pkg install xfce* libxfce* mousepad tigervnc -y

echo "vncserver -geometry 1600x900 -name remote-desktop :1" > $PREFIX/bin/desktop-xfce
echo "vncserver -kill :1" > $PREFIX/bin/desktop-stop

mkdir ~/.vnc
echo "#!/bin/bash
xrdb $HOME/.Xresources
startxfce4" > ~/.vnc/xstartup

chmod +x ~/.vnc/xstartup
chmod +x $PREFIX/bin/desktop-xfce
chmod +x $PREFIX/bin/desktop-stop

clear
echo " "
echo "Vnc Server address will run at 127.0.0.1:5901"
echo " "
echo "Command to start 'desktop-xfce' and stop 'desktop-stop'"
echo " "

bash desktop-xfce
break
    ;;
    
    "Quit")
      echo "backing"
      cd ~/crazy && bash crazy
      break
      ;;
    *) echo "Invalid option"
      ;;
  esac
done
;;
  2) echo "Install hacking tools"
  options=("FaceBook" "more" "Quit")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
"FaceBook")
options=("fishing" "cloning" "back")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
"fishing")
cd && apt install git -y && apt install python3 -y && git clone https://github.com/KasRoudra/PyPhisher && cd PyPhisher && cd files && pip install -r requirements.txt && cd .. && python3 pyphisher.py
;;

"cloning")
cd && apt install git -y && apt install python3 -y && git clone https://github.com/HARRY-EXE/HARRYv6 && git clone https://github.com/Masager/Dump
;;

"back")
cd ~/crazy && bash crazy
 exit 0
      ;;
    *) echo "Invalid option"
      ;;
  esac
done
;;
"more")
options=("install all hacking tools" "email" "repos" "back")
echo "Please select an option:"
PS4="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
  "install all hacking tools")
cd
    apt install python3 -y
    apt install git -y
apt install wget -y
    apt install bmon -y
    apt install neofetch -y
    apt install zip -y
    apt install w3m -y
    apt update
    apt upgrade -y
    apt update
    cd
git clone https://github.com/vaginessa/Tool-X

    cd Tool-X

    bash install.aex
exit 0
    ;;

  "email")
    cd
rm -rf mosint
apt install git -y && apt install golang -y
git clone https://github.com/alpkeskin/mosint
cd mosint
go install -v github.com/alpkeskin/mosint/v3/cmd/mosint@latest
rm -rf ~/.mosint.yaml
cp example-config.yaml ~/.mosint.yaml
cd v3/cmd/mosint
    ;;

  "repos")
    cd
    correct_password="sajan"

    # Prompt the user for the password
    echo "Enter the password:"
    read password

    # Check if the password is correct
    if [[ "$password" == "$correct_password" ]]; then
      echo "Correct password"
      git clone https://github.com/sajanchhetri/fbtick
wget https://download1479.mediafire.com/pkqwmkl9g7fgcHto29BLKd0RI-abO4R7xI3x5IQ4nbwXuCxdy4MwGY4TLQMwW7aSgKa2AZ7blVVrPMpzBrEp1tXCwBj5Erna2mNlopaf8G9sT2xroVwzHLJcgc9RSnIANU2tQL_0Vif61ubJ0VcXnkBkQp91lAetGdQr4IYfJ-IFFdQ/rxppnti22opxi2q/HARRYv6-OK.txt
      git clone https://github.com/sajanchhetri/pwd
    else
      echo "Incorrect password"
    fi
    ;;

  "back")
    cd ~/crazy && bash crazy
    exit 0
    ;;

  *)
    echo "Invalid option"
    ;;
  esac
done
;;
"Quit")
      echo "backing"
      cd ~/crazy && bash crazy
      break
      ;;
    *) echo "Invalid option"
      ;;
  esac
done
;;
  3) echo "Upgrading script..."
  cd ~
  rm -rf crazy
git clone https://github.com/sajanchhetri/crazy
cd ~/crazy && bash crazy
     ;;
  4) echo "CLI INSTALLATION"
   options=("KALI" "UBUNTU" "Quit")
echo "Please select an option:"
PS3="Enter your choice: "
select opt in "${options[@]}"
do
  case $opt in
 "KALI")
 cd
 termux-setup-storage
pkg install wget
wget -O install-nethunter-termux https://offs.ec/2MceZWr
chmod +x install-nethunter-termux
./install-nethunter-termux
break
;;
"UBUNTU")
cd
apt upgrade -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu22/ubuntu22.sh -O ubuntu22.sh && chmod +x ubuntu22.sh && bash ubuntu22.sh
break
;;
"Quit")
cd ~/crazy && bash crazy
break
;;
    *) echo "Invalid option"
      ;;
  esac
done
;;
  5) echo "Quitting..."
chmod +x crazy
chmod +x ~/crazy/cmd/email.sh
  cp ~/crazy/cmd/.bashrc ~/.bashrc
clear
     exit 0
     ;;
  *) echo "Invalid option. Please try again."
     ;;
esac
